version: "3"
services:
  bot-clony:
    container_name: bot-clony
    image: bot-clony
    # user: 1000:1000 # should be owner of volumes
    restart: always
    volumes:
      - "./bot.db:/usr/src/bot/bot.db"
      - "./allowed_params.pickle:/usr/src/bot/allowed_params.pickle"
      - "./banned_wordlist.txt:/usr/src/bot/banned_wordlist.txt"
    network_mode: bridge
    env_file:
      - ./.env
    logging:
      options:
        max-size: "5m"
        max-file: "1"

