version: "3"
services:
  bannerbot:
    container_name: bannerbot
    image: bannerbot
    # user: 1000:1000 # should be owner of volumes
    restart: always
    volumes:
      - "./bot.db:/usr/src/bot/bot.db"
    network_mode: bridge
    env_file:
      - ./.env
    logging:
      options:
        max-size: "5m"
        max-file: "1"

