version: "3"
services:
  pasture-bot:
    container_name: pasture-bot
    image: pasture-bot
    # user: 1000:1000 # should be owner of volumes
    restart: always
    volumes:
      - "./bot.db:/usr/src/bot/bot.db"
      - "./allowed_params.pickle:/usr/src/bot/allowed_params.pickle"
    network_mode: bridge
    env_file:
      - ./.env
    logging:
      options:
        max-size: "5m"
        max-file: "1"

